### ISSUE TITLE
Nicknames with a null character breaking message formatting

### ISSUE THREAD

**Issue by headsmasher8557** [fofl12/scriptsoup#5]
Luau (on Roblox) has a bug where characters that come after a null character (ASCII 0) don't get rendered.

Comradio clients get affected by this with nicknames, mostly by not being able to display the rest of the message.

**Comment by fofl12** [comment]
This can only be prevented on the clients using comradio2. The protocol cannot prevent this itself, due to the decentralized nature of it.
